services:
  - type: web
    name: physics-lab-chatbot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 16.20.0  # Add specific node version
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000